Feature/swiper delete notifications
AdrianoValadaresFrwk/fidelidade_android pull request #71
Opened 2022-01-05 19:06 UTC by Raiffep

Criação de swiper para habilitar funcionalidade de deslizar a notificação para a direita e deletar a mesma da lista

2022-01-05 20:12 UTC, gpigatto requested changes
Precisa resolver os conflitos antes, um jeito fácil é:

git checkout main
git pull
git checkout feature/swiper_delete_notifications
git merge main

No vscode vai aparecer as partes com conflito na aba do git, corrigi elas e em seguida:

git add .
git commit -m 'merge main'
git push origin feature/swiper_delete_notifications

2022-01-05 21:37 UTC, Raiffep commented
> O arquivo que está dando conflito não é pra subir nos merges, confirma se ele esta listado no seu .gitignore

Pois é, acabei de ver isso e ele está sim no .gitignore. De toda forma ajustei o conflito

2022-01-06 11:48 UTC, gpigatto approved these changes
ele tá listado msm, mas n esta sendo ignorado, vou ver oq pode ser

2022-01-06 12:40 UTC, AdrianoValadaresFrwk approved these changes

2022-01-06 12:41 UTC, merged